### PR TITLE
FEAT : Added A Hover Effect & ToolTips In Side Bar Buttons For Better User Experience.

### PR DESCRIPTION
**Pull request by Rudrajiii**
Issue #20 

# Sidebar Navigation Enhancement

Enhancements in sidebar navigation for improved usability and accessibility.

## Overview

The sidebar now includes:
1. **Hover Effects**: Each button highlights when hovered, providing visual feedback for easier navigation.
2. **Tooltips**: Tooltips with descriptive text display on hover, helping users identify the purpose of each button.

These changes aim to make navigation more intuitive, particularly for new users or those unfamiliar with the icons.

## Reason for the Change

Before this enhancement, sidebar buttons lacked hover effects, making it challenging for users to determine each button’s function. The addition of hover effects and tooltips enhances user experience by making the sidebar more navigable and user-friendly.

## Here is The Result ~

https://github.com/user-attachments/assets/2673f255-0fb4-44fd-abdb-103d03fb5615

With these enhancements, the sidebar navigation is now more polished and accessible, improving the overall user experience.

### CODE REVIEW

**Comment by sahilatahar** [comment]
@Rudrajiii Thanks for showing interest in contributing to this project. It's a great idea.

**Remember some points:**

1. Create a file for button tooltip style and put it in. If you need that style in many places.
2. Do not delete any file like you have deleted `.env.example`

**How did you handle the tooltip on mobile devices?**

**Comment by Rudrajiii** [comment]
Hey @sahilatahar Thanks For Clarifying.
i have updated the pull request check it out .
updates
1. created an new file for those styles as per you mentioned.
2. created `.env.example` back again .
3. for the small devices i disable the tooltip functionality but the enabled the hover effect . i tried to set the position of tooltip dynamically as per the screen size but it seems like does not really work also for smaller screen size i don't think the `tooltip` is import that much and does really look good that much so i decided to keep it only for the desktop devices.

and here is the final result's 



https://github.com/user-attachments/assets/69107aa6-8ebf-4de9-995a-f2513f7c1f4b

**Comment by sahilatahar** [comment]
@Rudrajiii Everything looks fine. Just one thing `client` doesn't have `.env.example`.

**Comment by Rudrajiii** [comment]
@sahilatahar  I have added in client also but some how it's not showing you can check my 3rd commit `made tooltipStyles.ts to use it's styles globaly. and .env.example added again.` also it is already there ..

**Comment by Rudrajiii** [comment]
@sahilatahar  i have found a tiny bug in readme file 
Screen Shot Attached ~
image
in the readme.md file you mentioned that rename the existing `.env.example` file to `.env` but for this `.env.example` gets deleted automatically so it should tell contributors to create a new `.env` file rather rename the file so that `.env.example` keeps uneffected.

**Pull request merged**
